version: '2.2'
services:
  color-analysis:
    container_name: color
    build:
      context: ColorAnalysis
      dockerfile: Dockerfile
    image: slashuzero/multi-card-analysis:color-analysis
    ports:
      - "8081:8081"

  match-analysis:
    container_name: match
    build:
      context: MatchAnalysis
      dockerfile: Dockerfile
    image: slashuzero/multi-card-analysis:match-analysis
    ports:
      - "8083:8083"

  deck-sys:
    container_name: deck
    build:
      context: DeckSys
      dockerfile: Dockerfile
    image: slashuzero/multi-card-analysis:deck-sys
    ports:
      - "8082:8082"

  straight-analysis:
    container_name: straight
    build:
      context: StraightAnalysis
      dockerfile: Dockerfile
    image: slashuzero/multi-card-analysis:straight-analysis
    ports:
      - "8084:8084"
  interpretor:
    container_name: interpretor
    build:
      context: Interpretor
      dockerfile: Dockerfile
    image: slashuzero/multi-card-analysis:interpretor
    ports:
      - "8085:8085"

  card-sys-front:
    container_name: card-sys-front
    build:
      context: card-sys-front
      dockerfile: Dockerfile
    image: slashuzero/multi-card-analysis:card-sys-front
    ports:
      - "4200:80"






